# Generated by Django 4.2.3 on 2023-09-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='部门名称')),
                ('deptId', models.IntegerField(verbose_name='部门id')),
                ('parentId', models.CharField(default='null', max_length=32, verbose_name='上级部门ID')),
                ('children', models.CharField(default='null', max_length=256, verbose_name='下级部门')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(default='123456', max_length=32, verbose_name='密码')),
                ('deptId', models.CharField(max_length=32, verbose_name='所属部门')),
                ('type', models.IntegerField(default=0, verbose_name='类型身份')),
            ],
        ),
    ]
