# Generated by Django 4.2.3 on 2023-09-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Defect_Management_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='deptId',
        ),
    ]
