# Generated by Django 4.2.3 on 2023-09-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Defect_Management_backend', '0002_remove_department_deptid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='children',
        ),
        migrations.AddField(
            model_name='department',
            name='hasChildren',
            field=models.BooleanField(max_length=256, null=True, verbose_name='是否有下级部门'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parentId',
            field=models.CharField(default=0, max_length=32, verbose_name='上级部门ID'),
        ),
    ]
