# Generated by Django 4.2.3 on 2023-09-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Defect_Management_backend', '0003_remove_department_children_department_haschildren_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hasChildren',
            field=models.CharField(max_length=256, null=True, verbose_name='是否有下级部门'),
        ),
    ]
