# Generated by Django 4.2.3 on 2023-10-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Defect_Management_backend', '0005_alter_department_parentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='项目名称')),
                ('desc', models.CharField(max_length=128, verbose_name='项目描述')),
                ('dept', models.CharField(max_length=32, verbose_name='项目部门')),
                ('member', models.CharField(max_length=256, verbose_name='项目成员')),
                ('status', models.CharField(max_length=16, verbose_name='项目状态')),
                ('createTime', models.DateField(verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='parentId',
            field=models.IntegerField(default=0, verbose_name='上级部门ID'),
        ),
    ]
