# Generated by Django 4.2.3 on 2023-10-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Defect_Management_backend', '0007_defect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('priority', models.CharField(max_length=16, verbose_name='优先级')),
                ('iteration', models.CharField(max_length=32, verbose_name='迭代')),
                ('state', models.CharField(default='进行中', max_length=32, verbose_name='状态')),
                ('handler', models.CharField(max_length=32, verbose_name='处理人')),
                ('start', models.CharField(max_length=32, verbose_name='预计开始')),
                ('end', models.CharField(max_length=32, verbose_name='预计结束')),
                ('desc', models.CharField(max_length=256, verbose_name='需求描述')),
                ('pid', models.CharField(max_length=16, verbose_name='所属项目ID')),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='pid',
            field=models.CharField(max_length=12, null=True, verbose_name='所属项目ID'),
        ),
    ]
