# Generated by Django 4.2.3 on 2023-10-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Defect_Management_backend', '0008_requirement_defect_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defect',
            old_name='createPerson',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='defect',
            old_name='debug',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='defect',
            old_name='dealPerson',
            new_name='handler',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='belong',
        ),
        migrations.AddField(
            model_name='defect',
            name='iteration',
            field=models.CharField(max_length=32, null=True, verbose_name='迭代'),
        ),
    ]
