# Generated by Django 4.2.3 on 2023-10-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Defect_Management_backend', '0010_rename_status_defect_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='state',
            field=models.CharField(default='进行中', max_length=16, verbose_name='缺陷状态'),
        ),
    ]
