# Generated by Django 4.2.3 on 2023-10-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Defect_Management_backend', '0011_alter_defect_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='createTime',
            field=models.CharField(max_length=64, verbose_name='创建时间'),
        ),
    ]
