# Generated by Django 4.2.3 on 2023-11-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Defect_Management_backend', '0015_testcase_level_alter_defect_createtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='connectionCase',
            field=models.CharField(max_length=128, null=True, verbose_name='关联的用例'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='connectionDefect',
            field=models.CharField(max_length=128, null=True, verbose_name='关联的缺陷'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='createTime',
            field=models.CharField(default='2023-11-02 03:13:53', max_length=64, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='createTime',
            field=models.CharField(default='2023-11-02 03:13:53', max_length=64, verbose_name='创建时间'),
        ),
    ]
