# Generated by Django 4.2.3 on 2023-11-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Defect_Management_backend', '0016_requirement_connectioncase_testcase_connectiondefect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='connectionCase',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='connectionDefect',
        ),
        migrations.AddField(
            model_name='defect',
            name='linkId',
            field=models.CharField(max_length=8, null=True, verbose_name='绑定用例ID'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='linkId',
            field=models.CharField(max_length=8, null=True, verbose_name='绑定需求ID'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='createTime',
            field=models.CharField(default='2023-11-03 06:53:50', max_length=64, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='createTime',
            field=models.CharField(default='2023-11-03 06:53:50', max_length=64, verbose_name='创建时间'),
        ),
    ]
