# Generated by Django 4.2.3 on 2023-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Defect_Management_backend', '0018_projectfile_alter_defect_createtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('state', models.CharField(default='打开', max_length=16, verbose_name='状态')),
                ('start', models.CharField(max_length=64, verbose_name='开始时间')),
                ('end', models.CharField(max_length=64, verbose_name='结束时间')),
                ('pid', models.CharField(max_length=16, verbose_name='所属项目ID')),
            ],
        ),
        migrations.AlterField(
            model_name='defect',
            name='createTime',
            field=models.CharField(default='2023-11-22 08:32:56', max_length=64, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='createTime',
            field=models.CharField(default='2023-11-22 08:32:56', max_length=64, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='createTime',
            field=models.CharField(default='2023-11-22 08:32:56', max_length=64, verbose_name='创建时间'),
        ),
    ]
