# Generated by Django 4.2.3 on 2023-12-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Defect_Management_backend', '0021_alter_defect_createtime_alter_defect_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='document_type',
            field=models.CharField(max_length=32, null=True, verbose_name='文档类型'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='createTime',
            field=models.CharField(default='2023-12-04 08:35:19', max_length=64, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='createTime',
            field=models.CharField(default='2023-12-04 08:35:19', max_length=64, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='pid',
            field=models.CharField(max_length=16, null=True, verbose_name='所属项目ID'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='createTime',
            field=models.CharField(default='2023-12-04 08:35:19', max_length=64, verbose_name='创建时间'),
        ),
    ]
